interface Teacher {
  acronym: string;
  fullName: string;
  faculty: string | null;
  designation: string | null;
  phone: string | null;
  email: string | null;
}

export const teachers: Teacher[] = [
  {
    acronym: "SAB",
    fullName: "Sabia Akter Bhuiyan",
    faculty: "CSE",
    designation: "Assistant Professor",
    phone: "01714506159",
    email: "aktersabia@yahoo.com",
  },
  {
    acronym: "SKB",
    fullName: "Shafkat Kibria",
    faculty: "CSE",
    designation: "Assistant Professor",
    phone: "01972601050",
    email: "shafkat@lus.ac.bd",
  },
  {
    acronym: "EBH",
    fullName: "Md. Ebrahim Hossain",
    faculty: "CSE",
    designation: "Assistant Professor",
    phone: "01733688612",
    email: "ebrahim.cse@lus.ac.bd",
  },
  {
    acronym: "RLP",
    fullName: "Rana M Luthfur Rahman Pir",
    faculty: "CSE",
    designation: "Assistant Professor",
    phone: "01763460076",
    email: "ranapir_cse@lus.ac.bd",
  },
  {
    acronym: "KJH",
    fullName: "Kazi Md. Jahid Hasan",
    faculty: "CSE",
    designation: "Assistant Professor & Head",
    phone: "01676480060",
    email: "jahidce@lus.ac.bd",
  },
  {
    acronym: "AHQ",
    fullName: "Arafat Habib Quraishi",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01914487146",
    email: "arafat@lus.ac.bd",
  },
  {
    acronym: "STA",
    fullName: "Syeda Tamanna Alam Monisha",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01712953999",
    email: "monisha_cse@lus.ac.bd",
  },
  {
    acronym: "MSR",
    fullName: "Mohammad Shoaib Rahman",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01717001333",
    email: "shoaib_cse@lus.ac.bd",
  },
  {
    acronym: "PRB",
    fullName: "Prithwiraj Bhattacharjee",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01785043726",
    email: "prithwiraj_cse@lus.ac.bd",
  },
  {
    acronym: "AFZ",
    fullName: "Md. Arifuzzaman",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01998740789",
    email: "arif_cse@lus.ac.bd",
  },
  {
    acronym: "MJR",
    fullName: "Md. Jamaner Rahaman",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01310817573",
    email: "jamaner_cse@lus.ac.bd",
  },
  {
    acronym: "JIM",
    fullName: "Md. Jehadul Islam Mony",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01686749128",
    email: "mony_cse@lus.ac.bd",
  },
  {
    acronym: "DCP",
    fullName: "Dipta Chandra Paul",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01744420273",
    email: "dipta@lus.ac.bd",
  },
  {
    acronym: "SAZ",
    fullName: "Shahriar Arefin Zummon",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01623573213",
    email: "shahriar.arefin_cse@lus.ac.bd",
  },
  {
    acronym: "SMD",
    fullName: "Somapika Das",
    faculty: "CSE, LU",
    designation: "Lecturer",
    phone: "01772355879",
    email: "ssomapika@gmail.com",
  },
  {
    acronym: "ASD",
    fullName: "Aushtmi Deb",
    faculty: "CSE, LU",
    designation: "Lecturer",
    phone: "01785633171",
    email: "aushtmidev384@gmail.com",
  },
  {
    acronym: "JAC",
    fullName: "Md. Jalal Uddin Chowdhury",
    faculty: "CSE, LU",
    designation: "Lecturer",
    phone: "01646705394",
    email: "jalalchy101@gmail.com",
  },
  {
    acronym: "NAC",
    fullName: "Naeem Ahsan Chowdhury",
    faculty: "CSE, LU",
    designation: "Lecturer",
    phone: "01994900475",
    email: "naeemahsan711@gmail.com",
  },
  {
    acronym: "ZMM",
    fullName: "Zumana Islam Mou",
    faculty: "CSE, LU",
    designation: "Lecturer",
    phone: "01636365931",
    email: "izumana17@gmail.com",
  },
  {
    acronym: "RWA",
    fullName: "Rezwana Afrin",
    faculty: "CSE, LU",
    designation: "Lecturer",
    phone: "01797432758",
    email: "rezwanaridi18@gmail.com",
  },
  {
    acronym: "NJN",
    fullName: "Nargish Jahan",
    faculty: "CSE, LU",
    designation: "Part Time Lecturer",
    phone: "01759486292",
    email: "njlisa25@gmail.com",
  },
  {
    acronym: "PRP",
    fullName: "Puroby Roy Puja",
    faculty: "CSE, LU",
    designation: "Part Time Lecturer",
    phone: "01878070499",
    email: "pujapuroby@gmail.com",
  },
  {
    acronym: "SRR",
    fullName: "Md Sadekur Rahman Rani",
    faculty: "MATH, SUST",
    designation: "Lecturer",
    phone: "01737466765",
    email: "sustianroni@gmail.com",
  },
  {
    acronym: "SMN",
    fullName: "Mst. Shamima Nasrin",
    faculty: "MATH, SUST",
    designation: "Part Time Lecturer",
    phone: "01795780508",
    email: "mstshamima08@student.sust.edu",
  },
  {
    acronym: "AMH",
    fullName: "Md. Amranul Haque",
    faculty: "MATH, SUST",
    designation: "Lecturer",
    phone: "01815091979",
    email: "amranhq018@gmail.com",
  },
  {
    acronym: "NIR",
    fullName: "Nahidul Islam Rupom",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01641214872",
    email: "nahidul.rupom@gmail.com",
  },
  {
    acronym: "MHH",
    fullName: "Md. Mahdi Hossain Hira",
    faculty: "CSE, LU",
    designation: "Adjunct Lecturer",
    phone: "01772-757936",
    email: "bdmahdihira53@gmail.com",
  },
  {
    acronym: "SBT",
    fullName: "Sudipta Banik Trisha",
    faculty: "CSE, SEC",
    designation: "Adjunct Lecturer",
    phone: "01700-835172",
    email: "sudptatrisha.19@gmail.com",
  },
  {
    acronym: "AFR",
    fullName: "Ashfakur Rahman",
    faculty: "CSE, SEC",
    designation: "Adjunct Lecturer",
    phone: "01779-693679",
    email: "ashfakur.rahman79@gmail.com",
  },
  {
    acronym: "SPJ",
    fullName: "Soumik Paul Jisun",
    faculty: "CSE, SUST",
    designation: "Adjunct Lecturer",
    phone: "01742-332335",
    email: "spj.cse.lu@gmail.com",
  },
  {
    acronym: "AMD",
    fullName: "Ameya Debnath",
    faculty: "CSE, SUST",
    designation: "Adjunct Lecturer",
    phone: "01716-202230",
    email: "ameyadebnath@gmail.com",
  },
  {
    acronym: "NDK",
    fullName: "Nilavro Das Kabya",
    faculty: "CSE, NSU",
    designation: "Adjunct Lecturer",
    phone: "01704-048178",
    email: "kabyodas@gmail.com",
  },
  {
    acronym: "ABD",
    fullName: "Md. Abid Ashraf",
    faculty: "CSE, SEC",
    designation: "Adjunct Lecturer",
    phone: "01620-807971",
    email: "abidash03@gmail.com",
  },
  {
    acronym: "SDR",
    fullName: "S. M. Saydur Rahman",
    faculty: "MATH, SUST",
    designation: "Adjunct Assistant Professor",
    phone: "01675469943",
    email: "saydur-mat@sust.edu",
  },
  {
    acronym: "MRH",
    fullName: "Md. Rashidul Hasan",
    faculty: "PH, LU",
    designation: "Assistant Professor",
    phone: "01728885514",
    email: "rashidulhasan067@gmail.com",
  },
  {
    acronym: "MSI",
    fullName: "Dr Mohammad Sayful Islam",
    faculty: "MATH, SUST",
    designation: "Adjunct Professor",
    phone: "01775484990",
    email: "sayful-mat@sust.edu",
  },
  {
    acronym: "MRI",
    fullName: "Rafiqul Islam",
    faculty: "EEE, LU",
    designation: "Assistant Professor",
    phone: "01716446071",
    email: "rafiqulzyl@lus.ac.bd",
  },
  {
    acronym: "AFB",
    fullName: "Afshana Begum",
    faculty: "EEE, LU",
    designation: "Lecturer",
    phone: "01517161185",
    email: "afshana_eee@lus.ac.bd",
  },
  {
    acronym: "IAC",
    fullName: "Ishmam Ahmed Chowdhury",
    faculty: "EEE, LU",
    designation: "Lecturer",
    phone: "01723000891",
    email: "ishmamahmed_eee@lus.ac.bd",
  },
  {
    acronym: "MLH",
    fullName: "Md. Luthful Hasan",
    faculty: "EEE, LU",
    designation: "Part Time Lecturer",
    phone: "01751386486",
    email: "luthful99@gmail.com",
  },
  {
    acronym: "SHB",
    fullName: "Shajeda Begum",
    faculty: "EEE, LU",
    designation: "Part Time Lecturer",
    phone: "01831754375",
    email: "sajidabegum041196@gmail.com",
  },
  {
    acronym: "RUM",
    fullName: "Ruma Das",
    faculty: "EEE, LU",
    designation: "Part Time Lecturer",
    phone: "01635249304",
    email: "sustruma@gmail.com",
  },
  {
    acronym: "AHO",
    fullName: "Md. Akram Hossain",
    faculty: "Chem, SUST",
    designation: "Part Time Lecturer",
    phone: null,
    email: null,
  },
  {
    acronym: "BLA",
    fullName: "Dr. Belal Ahmed",
    faculty: "Chem, SUST",
    designation: "Adjunct Associate Professor",
    phone: "01714609507",
    email: "belal-che@sust.edu",
  },
  {
    acronym: "DD",
    fullName: "Dipto Das",
    faculty: "Chem, SUST",
    designation: "Part Time Lecturer",
    phone: null,
    email: null,
  },
  {
    acronym: "TSC",
    fullName: "Tanjima Siddika Chandni",
    faculty: "ARCH, LU",
    designation: "Assistant Professor",
    phone: "01912581499",
    email: "tanjima.arch@lus.ac.bd",
  },
  {
    acronym: "SMA",
    fullName: "Syed Mohsin Ali",
    faculty: "ARCH, LU",
    designation: "Assistant Professor",
    phone: "01742824848",
    email: "mohsin@lus.ac.bd",
  },
  {
    acronym: "SA",
    fullName: "Salina Akther",
    faculty: "ARCH, LU",
    designation: "Assistant Professor",
    phone: "01918774428",
    email: "salinasumi@lus.ac.bd",
  },
  {
    acronym: "SMHS",
    fullName: "Shah Md. Hasin Shad",
    faculty: "ARCH, LU",
    designation: "Lecturer",
    phone: "01673259694",
    email: "hasinshad@lus.ac.bd",
  },
  {
    acronym: "FHJ",
    fullName: "Farhana Hoque",
    faculty: "ARCH, LU",
    designation: "Lecturer",
    phone: "01675972839",
    email: "farhanahoque_arch@lus.ac.bd",
  },
  {
    acronym: "AT",
    fullName: "Azima Tabassum",
    faculty: "ARCH, LU",
    designation: "Lecturer",
    phone: "01744545805",
    email: "azima_arch@lus.ac.bd",
  },
  {
    acronym: "KKS",
    fullName: "Kanak Kanti Saha",
    faculty: "ARCH, LU",
    designation: "Lecturer",
    phone: "01748137412",
    email: "kanak_arch@lus.ac.bd",
  },
  {
    acronym: "BU",
    fullName: "Burhan Uddin",
    faculty: "ARCH, LU",
    designation: "Lecturer",
    phone: "01740994597",
    email: "burhan_arch@lus.ac.bd",
  },
  {
    acronym: "AS",
    fullName: "Arpan Shil",
    faculty: "ARCH, LU",
    designation: "Lecturer",
    phone: "01827879188",
    email: "arpan_arch@lus.ac.bd",
  },
  {
    acronym: "MSM",
    fullName: "Dr. Mohammad Shahansha Molla",
    faculty: "BuA, LU",
    designation: "Associate Professor",
    phone: "01619610017",
    email: "shahansha@lus.ac.bd",
  },
  {
    acronym: "JA",
    fullName: "Dr. Md. Jahangir Alam",
    faculty: "BuA, LU",
    designation: "Associate Professor",
    phone: "01711009899",
    email: "jalam160@lus.ac.bd",
  },
  {
    acronym: "WA",
    fullName: "Ms. Wahida Akther",
    faculty: "BuA, LU",
    designation: "Assistant Professor",
    phone: "01819538975",
    email: "wahidaala@lus.ac.bd",
  },
  {
    acronym: "AAA",
    fullName: "Mr. Anwar Ahmad Arif",
    faculty: "BuA, LU",
    designation: "Assistant Professor",
    phone: "01712661446",
    email: "aaarif@lus.ac.bd",
  },
  {
    acronym: "MSI",
    fullName: "Md. Shamimul Islam",
    faculty: "BuA, LU",
    designation: "Assistant Professor",
    phone: "01918942572",
    email: "mshamim09@lus.ac.bd",
  },
  {
    acronym: "HRK",
    fullName: "Mr. Md. Hafizur Rahman Khan",
    faculty: "BuA, LU",
    designation: "Assistant Professor",
    phone: "01737401135",
    email: "hafizurrahman_bua@lus.ac.bd",
  },
  {
    acronym: "AMC",
    fullName: "Mr. Abdul Muhith Chowdhury",
    faculty: "BuA, LU",
    designation: "Assistant Professor",
    phone: "01717497366",
    email: "muhith@lus.ac.bd",
  },
  {
    acronym: "FH",
    fullName: "Mr. Farhad Hossain",
    faculty: "BuA, LU",
    designation: "Assistant Professor",
    phone: "01611504166",
    email: "farhad@lus.ac.bd",
  },
  {
    acronym: "JS",
    fullName: "Ms. Jaynob Sarker",
    faculty: "BuA, LU",
    designation: "Assistant Professor",
    phone: "01683931272",
    email: "jaynobsarker@lus.ac.bd",
  },
  {
    acronym: "RA",
    fullName: "Mr. Riju Ahmed",
    faculty: "BuA, LU",
    designation: "Lecturer (MIS)",
    phone: "01643480168",
    email: "riju_bua@lus.ac.bd",
  },
  {
    acronym: "SAR",
    fullName: "Syed Aminur Rahman",
    faculty: "BuA, LU",
    designation: "Part Time Lecturer",
    phone: "01814497056",
    email: "numanpsc@gmail.com",
  },
  {
    acronym: "IHM",
    fullName: "Md Imran Hossain Milon",
    faculty: "BuA, LU",
    designation: "Part Time Lecturer",
    phone: "01798736315",
    email: "miloneco26@gmail.com",
  },
  {
    acronym: "MKR",
    fullName: "Mahfuja Khatun Rima",
    faculty: "BuA, LU",
    designation: "Part Time Lecturer",
    phone: "01629685647",
    email: "mahfujakhatun255@gmail.com",
  },
  {
    acronym: "MKN",
    fullName: "Marjana Khan Nipa",
    faculty: "BuA, LU",
    designation: "Part Time Lecturer",
    phone: "01718197401",
    email: "m.nipa@hotmail.com",
  },
  {
    acronym: "FI",
    fullName: "Fakrul Islam",
    faculty: "BuA, LU",
    designation: "Part Time Lecturer",
    phone: "01775848483",
    email: "fakrulislamsust@gmail.com",
  },
  {
    acronym: "NNN",
    fullName: "Nowshin Noweer Nisa",
    faculty: "BuA, LU",
    designation: "Part Time Lecturer",
    phone: "01777051795",
    email: "nowshin.n.nisa@gmail.com",
  },
  {
    acronym: "NI",
    fullName: "NAIMUL ISLAM",
    faculty: "Civil, LU",
    designation: "Lecturer, LU",
    phone: "01774455922",
    email: "naimulislam_ce@lus.ac.bd",
  },
  {
    acronym: "MI",
    fullName: "MOMINUL ISLAM",
    faculty: "Civil, LU",
    designation: "Lecturer, LU",
    phone: "01788405033",
    email: "mominul_ce@lus.ac.bd",
  },
  {
    acronym: "GSB",
    fullName: "MD. GOLAM SHAHRIA BHUYAIN",
    faculty: "Civil, LU",
    designation: "Lecturer, LU",
    phone: "01719706550",
    email: "shahria_ce@lus.ac.bd",
  },
  {
    acronym: "TJK",
    fullName: "TANJILA JAHAN KHAN",
    faculty: "Civil, LU",
    designation: "Lecturer, LU",
    phone: "01734804420",
    email: "tanjila_ce@lus.ac.bd",
  },
  {
    acronym: "ARK",
    fullName: "A R M KAMRUZZAMAN",
    faculty: "Civil, LU",
    designation: "Lecturer, LU",
    phone: "01758534638",
    email: "kamruzzaman021998@gmail.com",
  },
  {
    acronym: "MSU",
    fullName: "Md. Salauddin Ahmed",
    faculty: "EEE, LU",
    designation: "Part Time Lecturer",
    phone: "01779907946",
    email: "salauddinsust89@gmail.com",
  },
  {
    acronym: "IA",
    fullName: "Istheak Ahmed",
    faculty: "EEE, LU",
    designation: "Part Time Lecturer",
    phone: "01722593128",
    email: "istheak2016@gmail.com",
  },
  {
    acronym: "NRN",
    fullName: "Nilima Rani Nath",
    faculty: "EEE, LU",
    designation: "Part Time Lecturer",
    phone: "01732162252",
    email: "nilimazimly@gmail.com",
  },
  {
    acronym: "SA",
    fullName: "Shammi Akter",
    faculty: "English, LU",
    designation: "Assistant Professor",
    phone: "01674764323",
    email: "shammiakter@lus.ac.bd",
  },
  {
    acronym: "TS",
    fullName: "Touhida Sultana",
    faculty: "English, LU",
    designation: "Assistant Professor",
    phone: "01748515285",
    email: "touhida@lus.ac.bd",
  },
  {
    acronym: "AASH",
    fullName: "Ashfaque Ahmad Shovon",
    faculty: "English, LU",
    designation: "Lecturer",
    phone: "01619835466",
    email: "ashfaque_shovon@hotmail.com",
  },
  {
    acronym: "SNM",
    fullName: "Syeda Nazia Mahbuba",
    faculty: "English, LU",
    designation: "Lecturer",
    phone: "01790301830",
    email: "snazia_eng@lus.ac.bd",
  },
  {
    acronym: "NSD",
    fullName: "Nadia Sultana Daizy",
    faculty: "English, LU",
    designation: "Lecturer",
    phone: "01785662971",
    email: "nadia_eng@lus.ac.bd",
  },
  {
    acronym: "MAO",
    fullName: "Md. Ali Omar",
    faculty: "English, LU",
    designation: "Lecturer",
    phone: "01538203757",
    email: "aliomar_eng@lus.ac.bd",
  },
  {
    acronym: "OKM",
    fullName: "Omme Kulsum Mili",
    faculty: "English, LU",
    designation: "Lecturer",
    phone: "01776689260",
    email: "mili_eng@lus.ac.bd",
  },
  {
    acronym: "HM",
    fullName: "Humaira Mizan",
    faculty: "English, LU",
    designation: "Lecturer",
    phone: "01685563318",
    email: "humairaeng@lus.ac.bd",
  },
  {
    acronym: "SH",
    fullName: "Sanjida Haque",
    faculty: "English, LU",
    designation: "Lecturer",
    phone: "01867473283",
    email: null,
  },
  {
    acronym: "JR",
    fullName: "Jui Roy",
    faculty: "LAW, LU",
    designation: "Part Time Lecturer",
    phone: "01818-640688",
    email: "jui.roy1952@gmail.com",
  },
  {
    acronym: "SDD",
    fullName: "Swarup Das Dipto",
    faculty: "LAW, LU",
    designation: "Part Time Lecturer",
    phone: "01742-977744",
    email: "swarupdipto@gmail.com",
  },
  {
    acronym: "MTU",
    fullName: "Mohammed Taj Uddin",
    faculty: "Statistics, SUST",
    designation: "Adjunct Professor",
    phone: "01716348194",
    email: "mtajstat@yahoo.com",
  },
  {
    acronym: "SIC",
    fullName: "Md. Sakib Ibtidha Chy.",
    faculty: null,
    designation: "Part Time Lecturer",
    phone: "01675469437",
    email: "sakibibtida@gmail.com",
  },
  {
    acronym: "NNP",
    fullName: "Nazmun Nahar Papri",
    faculty: "CE, LU",
    designation: "Lecturer",
    phone: "01762912958",
    email: "npapri21@gmail.com",
  },
  {
    acronym: "PR",
    fullName: "Parama Rahman",
    faculty: "PH",
    designation: null,
    phone: "1616168091",
    email: null,
  },
  {
    acronym: "MRT",
    fullName: "Muntaha",
    faculty: "PH",
    designation: null,
    phone: "8801558093664",
    email: null,
  },
  {
    acronym: "TSC",
    fullName: "Tanjima Siddika Chandni",
    faculty: "ARCH",
    designation: "Assistant Professor",
    phone: "01912581499",
    email: "tanjima.arch@lus.ac.bd",
  },
  {
    acronym: "SMA",
    fullName: "Syed Mohsin Ali",
    faculty: "ARCH",
    designation: "Assistant Professor",
    phone: "01742824848",
    email: "mohsin@lus.ac.bd",
  },
  {
    acronym: "SA",
    fullName: "Salina Akther",
    faculty: "ARCH",
    designation: "Assistant Professor",
    phone: "01918774428",
    email: "salinasumi@lus.ac.bd",
  },
  {
    acronym: "SMHS",
    fullName: "Shah Md. Hasin Shad",
    faculty: "ARCH",
    designation: "Lecturer",
    phone: "01673259694",
    email: "hasinshad@lus.ac.bd",
  },
  {
    acronym: "FHJ",
    fullName: "Farhana Hoque",
    faculty: "ARCH",
    designation: "Lecturer",
    phone: "01675972839",
    email: "farhanahoque_arch@lus.ac.bd",
  },
  {
    acronym: "AT",
    fullName: "Azima Tabassum",
    faculty: "ARCH",
    designation: "Lecturer",
    phone: "01744545805",
    email: "azima_arch@lus.ac.bd",
  },
  {
    acronym: "KKS",
    fullName: "Kanak Kanti Saha",
    faculty: "ARCH",
    designation: "Lecturer",
    phone: "01748137412",
    email: "kanak_arch@lus.ac.bd",
  },
  {
    acronym: "BU",
    fullName: "Burhan Uddin",
    faculty: "ARCH",
    designation: "Lecturer",
    phone: "01740994597",
    email: "burhan_arch@lus.ac.bd",
  },
  {
    acronym: "AS",
    fullName: "Arpan Shil",
    faculty: "ARCH",
    designation: "Lecturer",
    phone: "01827879188",
    email: "arpan_arch@lus.ac.bd",
  },
  {
    acronym: "ASC",
    fullName: "Abu Sayed Chowdhury",
    faculty: "ARCH",
    designation: "Adjunct Faculty",
    phone: "01746867199",
    email: "abucsayed@gmail.com",
  },
  {
    acronym: "MMA",
    fullName: "Dr. Mohammad Mostak Ahmed",
    faculty: "Bangla",
    designation: "Head, dept of Bangla",
    phone: "01715003049",
    email: "head_bangla@lus.ac.bd",
  },
  {
    acronym: "AMM",
    fullName: "Professor Dr. Abdul Majid Mian",
    faculty: "BuA",
    designation: "Professor",
    phone: "01712824341",
    email: "dr.amozid@gmail.com",
  },
  {
    acronym: "AMC",
    fullName: "Mr. Abdul Muhith Chowdhury",
    faculty: "BuA",
    designation: "Assistant Professor",
    phone: "01717497366",
    email: "muhith@lus.ac.bd",
  },
  {
    acronym: "FH",
    fullName: "Mr. Farhad Hossain",
    faculty: "BuA",
    designation: "Assistant Professor",
    phone: "01611504166",
    email: "farhad@lus.ac.bd",
  },
  {
    acronym: "RA",
    fullName: "Mr. Riju Ahmed",
    faculty: "BuA",
    designation: "Lecturer",
    phone: "01643480168",
    email: "riju_bua@lus.ac.bd",
  },
  {
    acronym: "JS",
    fullName: "Ms. Jaynob Sarker",
    faculty: "BuA",
    designation: "Assistant Professor",
    phone: "01683931272",
    email: "jaynobsarker@lus.ac.bd",
  },
  {
    acronym: "HRK",
    fullName: "Mr. Md. Hafizur Rahman Khan",
    faculty: "BuA",
    designation: "Assistant Professor",
    phone: "01737401135",
    email: "hafizurrahman_bua@lus.ac.bd",
  },
  {
    acronym: "AIC",
    fullName: "Mr. Ashraful Islam Chowdhury",
    faculty: "BuA",
    designation: "Assistant Professor",
    phone: "01823152929",
    email: "ashraful@lus.ac.bd",
  },
  {
    acronym: "AAA",
    fullName: "Mr. Anwar Ahmad Arif",
    faculty: "BuA",
    designation: "Assistant Professor",
    phone: "01712661446",
    email: "aaarif@lus.ac.bd",
  },
  {
    acronym: "JJJ",
    fullName: "Ms. Juhora Jamin Juha",
    faculty: "BuA",
    designation: "Assistant Professor",
    phone: "01775099906",
    email: "jamin_3011@lus.ac.bd",
  },
  {
    acronym: "ASP",
    fullName: "Mr. A.S.P Sufian Pabel",
    faculty: "BuA",
    designation: "Adjunct Lecturer",
    phone: "01754683875",
    email: "Sufianpabel11@gmail.com",
  },
  {
    acronym: "GSB",
    fullName: "Md. Golam Shahria Bhuyain",
    faculty: "CE",
    designation: "Lecturer",
    phone: "01719706550",
    email: "shahria_ce@lus.ac.bd",
  },
  {
    acronym: "RRC",
    fullName: "Rabiur Rahman Chowdhury",
    faculty: "CE",
    designation: "Lecturer",
    phone: "01770616331",
    email: "rabi_ce@lus.ac.bd",
  },
  {
    acronym: "BLA",
    fullName: "Dr. Belal Ahmed",
    faculty: "CE",
    designation: "Associate Professor, faculty of Chemistry, SUST",
    phone: "01714609507",
    email: "belal-che@sust.edu",
  },
  {
    acronym: "AHO",
    fullName: "Md. Akram Hossain",
    faculty: "CE",
    designation: "Adjunct Faculty",
    phone: "01979413529",
    email: "akramchesust26@gmail.com",
  },
  {
    acronym: "MMA",
    fullName: "Dr. Md Mahbubul Alam",
    faculty: "CE",
    designation: "Professor, faculty of Chemistry, SUST",
    phone: "01711200306",
    email: "mahbubana-che@sust.edu",
  },
  {
    acronym: "DD",
    fullName: "Dipto Das",
    faculty: "CE",
    designation: "Adjunct Faculty",
    phone: "01737567930",
    email: "dasdipto254@gmail.com",
  },
  {
    acronym: "JUR",
    fullName: "Mr. Jasim Uddin Rahat",
    faculty: "CE",
    designation: "Adjunct Faculty",
    phone: "01982814240",
    email: "jasimrahat@gmail.com",
  },
  {
    acronym: "RMK",
    fullName: "Mr. A. R. M. Kamruzzaman",
    faculty: "CE",
    designation: "Adjunct Faculty",
    phone: "01896150940",
    email: "kamruzzaman021998@gmail.com",
  },
  {
    acronym: "NI",
    fullName: "Mr. Naimul Islam",
    faculty: "CE",
    designation: "Lecturer",
    phone: "01774455922",
    email: "islamnaimul892@gmail.com",
  },
  {
    acronym: "TJK",
    fullName: "Ms. Tanjila Jahan Khan",
    faculty: "CE",
    designation: "Lecturer",
    phone: "01734804420",
    email: "tahjilajahan@gmail.com",
  },
  {
    acronym: "NJN",
    fullName: "Nargish Jahan",
    faculty: "CSE",
    designation: "Lecturer (Adjunct Faculty)",
    phone: "01759486292",
    email: "njlisa25@gmail.com",
  },
  {
    acronym: "AHQ",
    fullName: "Arafat Habib Quraishi",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01914487146",
    email: "arafat@lus.ac.bd",
  },
  {
    acronym: "SMD",
    fullName: "Somapika Das",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01772355879",
    email: "somapika_cse@lus.ac.bd",
  },
  {
    acronym: "PRP",
    fullName: "Purobi Roy Puja",
    faculty: "CSE",
    designation: "Lecturer (Adjunct Faculty)",
    phone: "01878070499",
    email: "pujapurby@gmail.com",
  },
  {
    acronym: "NAC",
    fullName: "Nayem Ahmed Chowdhury",
    faculty: "CSE",
    designation: "Lecturer (Adjunct Faculty)",
    phone: "01779875412",
    email: "naeemahsan711@gmail.com",
  },
  {
    acronym: "RWA",
    fullName: "Rezwana Afrin",
    faculty: "CSE",
    designation: "Lecturer (Adjunct Faculty)",
    phone: "01797432758",
    email: "rezwanaridi18@gmail.com",
  },
  {
    acronym: "ZMM",
    fullName: "Zumana Islam Mou",
    faculty: "CSE",
    designation: "Adjunct Lecturer,CSE, LU",
    phone: "01601135355",
    email: "izumana17@gmail.com",
  },
  {
    acronym: "SKB",
    fullName: "Shafkat Kibria",
    faculty: "CSE",
    designation: "Assistant Professor",
    phone: "01972601050",
    email: "shafkat@lus.ac.bd",
  },
  {
    acronym: "SMN",
    fullName: "Shamima Nasrin",
    faculty: "CSE",
    designation: "Adjunct Lecturer,CSE, LU",
    phone: "01795780508",
    email: "mstshamima08@student.sust.edu",
  },
  {
    acronym: "EBH",
    fullName: "Md. Ebrahim Hossain",
    faculty: "CSE",
    designation: "Assistant Professor",
    phone: "01733688612",
    email: "ebrahim.cse@lus.ac.bd",
  },
  {
    acronym: "MJR",
    fullName: "Md. Jamaner Rahaman",
    faculty: "CSE",
    designation: "Lecturer",
    phone: "01310817573",
    email: "jamaner_cse@lus.ac.bd",
  },
  {
    acronym: "NMC",
    fullName: "Nuzhat Madeha Chowdhury",
    faculty: "CSE",
    designation: "Adjunct Lecturer",
    phone: "01725986299",
    email: "nmchy01@gmail.com",
  },
  {
    acronym: "NHK",
    fullName: "Nasima Haque Khan",
    faculty: "EEE",
    designation: "Professor, Physics",
    phone: "01911458471",
    email: "nasima25@live.com",
  },
  {
    acronym: "MSU",
    fullName: "Md. Salauddin Ahmed",
    faculty: "EEE",
    designation: "Adjunct Lecturer, EEE, LU",
    phone: "01779907946",
    email: "salauddinsust89@gmail.com",
  },
  {
    acronym: "NRN",
    fullName: "Nilima Rani Nath",
    faculty: "EEE",
    designation: "Adjunct Lecturer, EEE, LU",
    phone: "01732162252",
    email: "nilimazimly@gmail.com",
  },
  {
    acronym: "AE",
    fullName: "Ahmed Estiak",
    faculty: "EEE",
    designation: "Adjunct Lecturer, EEE, LU",
    phone: "01515231744",
    email: "ahmedestiak14@gmail.com",
  },
  {
    acronym: "IA",
    fullName: "Istheak Ahmed",
    faculty: "EEE",
    designation: "Adjunct Lecturer, EEE, LU",
    phone: "01722593128",
    email: "istheak2016@gmail.com",
  },
  {
    acronym: "PPD",
    fullName: "Partha Prathim Das",
    faculty: "EEE",
    designation: "Adjunct Lecturer, EEE, LU",
    phone: "01726786876",
    email: "parthaprathim.cuet@gmail.com",
  },
  {
    acronym: "RK",
    fullName: "Dr. Md. Rezaul Karim",
    faculty: "ENG",
    designation: "Associate Professor",
    phone: "01711467396",
    email: "reza@lus.ac.bd",
  },
  {
    acronym: "SA",
    fullName: "Shammi Akter",
    faculty: "ENG",
    designation: "Assistant Professor",
    phone: "01674764323",
    email: "aktershammi26@gmail.com",
  },
  {
    acronym: "TS",
    fullName: "Touhida Sultana",
    faculty: "ENG",
    designation: "Assistant Professor",
    phone: "01911243565",
    email: "touhida@lus.ac.bd",
  },
  {
    acronym: "AASH",
    fullName: "Ashfaque Ahmad Shovon",
    faculty: "ENG",
    designation: "Lecturer",
    phone: "01619835466",
    email: "ashfaqueshovon_eng@lus.ac.bd",
  },
  {
    acronym: "SNM",
    fullName: "Syeda Nazia Mahbuba",
    faculty: "ENG",
    designation: "Lecturer",
    phone: "01790301830",
    email: "snazia_eng@lus.ac.bd",
  },
  {
    acronym: "NSD",
    fullName: "Nadia Sultana Daijy",
    faculty: "ENG",
    designation: "Lecturer",
    phone: "01785662971",
    email: "nadia_eng@lus.ac.bd",
  },
  {
    acronym: "OKM",
    fullName: "Omme Kulsum Mili",
    faculty: "ENG",
    designation: "Lecturer",
    phone: "01776689260",
    email: "mili_eng@lus.ac.bd",
  },
  {
    acronym: "MAO",
    fullName: "Ali Omar",
    faculty: "ENG",
    designation: "Lecturer",
    phone: "01538203757",
    email: "aliomar_eng@lus.ac.bd",
  },
  {
    acronym: "SH",
    fullName: "Sanjida Haq",
    faculty: "ENG",
    designation: "Lecturer",
    phone: "01867473283",
    email: "sanjidavabna999@gmail.com",
  },
  {
    acronym: "HM",
    fullName: "Humaira Mizan",
    faculty: "ENG",
    designation: "Lecturer",
    phone: "01685563318",
    email: "humaira_eng@lus.ac.bd",
  },
  {
    acronym: "MAK",
    fullName: "Dr. Maimul Ahsan Khan",
    faculty: "LAW",
    designation: "Professor, Law, LU",
    phone: "01318251984",
    email: "khanmaimul@lus.ac.bd",
  },
  {
    acronym: "AMC",
    fullName: "Md Abdul Musabbir Chowdhury",
    faculty: "LAW",
    designation: "Assistant Professor, Law, LU",
    phone: "01717568792",
    email: "musabbirchy@lus.ac.bd",
  },
  {
    acronym: "AAM",
    fullName: "Abdullah Al-Mamun",
    faculty: "LAW",
    designation: "Assistant Professor, Law, LU",
    phone: "01716-604241",
    email: "mamundu201@gmail.com",
  },
  {
    acronym: "AU",
    fullName: "Asraf Uddin",
    faculty: "LAW",
    designation: "Lecturer, Law, LU",
    phone: "01520-103242",
    email: "asrafuddin@lus.ac.bd",
  },
  {
    acronym: "RK",
    fullName: "Md. Rezaul Karim",
    faculty: "LAW",
    designation: "Lecturer, Law, LU",
    phone: "01734-359534",
    email: "kazirezadu@gmail.com",
  },
  {
    acronym: "MH",
    fullName: "Mr. Md. Momin Hossain",
    faculty: "LAW",
    designation: "Lecturer",
    phone: "01833008031",
    email: "momin_law@lus.ac.bd",
  },
  {
    acronym: "SDD",
    fullName: "Mr. Swarup Das Dipto",
    faculty: "LAW",
    designation: "Adjunct Lecturer",
    phone: "01742977744",
    email: "swarupdipto@gmail.com",
  },
  {
    acronym: "KSI",
    fullName: "Mr. Khandaker Shariful Islam",
    faculty: "LAW",
    designation: "Lecturer",
    phone: "01521205742",
    email: "Shariful_law@lus.ac.bd",
  },
  {
    acronym: "PDB",
    fullName: "Mr. Promit Dipto Biswas",
    faculty: "LAW",
    designation: "Lecturer",
    phone: "01636666333",
    email: "promitdiptobiswas@gmail.com",
  },
  {
    acronym: "DSC",
    fullName: "Dr. SSRRina Farida Chowdhury",
    faculty: "PH",
    designation: "Lecturer",
    phone: "01676739798",
    email: "dr.sSRRinachowdhury@lus.ac.bd",
  },
  {
    acronym: "MHB",
    fullName: "Musa. Halima Begum",
    faculty: "PH",
    designation: "Associate Professor",
    phone: "019 1394 6475",
    email: "musa.halimabegum@yahoo.com",
  },
  {
    acronym: "MRH",
    fullName: "Md. Rashidul Hasan",
    faculty: "PH",
    designation: "Assistant Proessor",
    phone: "01728885514",
    email: "rashidulhasan067@gmail.com",
  },
  {
    acronym: "SIC",
    fullName: "Sakib Ibtida Chowdhury",
    faculty: "PH",
    designation: "Adjunct Faculty",
    phone: "01675469437",
    email: "ibtidachowdhury48@gmail.com",
  },
  {
    acronym: "MTU",
    fullName: "Dr. Md. Taj uddin",
    faculty: "PH",
    designation: "Adjunct Faculty (Professor)",
    phone: "01716348194",
    email: null,
  },
  {
    acronym: "RZR",
    fullName: "Rahmatul Zannat",
    faculty: "PH",
    designation: "Adjunct Faculty",
    phone: "01770329512",
    email: "rahmatulzannat@gmail.com",
  },
  {
    acronym: "NT",
    fullName: "Nishat Tasneem",
    faculty: "PH",
    designation: "Adjunct Faculty",
    phone: "01600340771",
    email: "nishat.tasneem71@gmail.com",
  },
  {
    acronym: "MAH",
    fullName: "Md. Abdul Halim",
    faculty: "THM",
    designation: "Lecturer",
    phone: "01817184947",
    email: "halim@lus.ac.bd",
  },
  {
    acronym: "ISH",
    fullName: "Mr. Iehit Sharma",
    faculty: "THM",
    designation: "Lecturer",
    phone: "01819848464",
    email: "iehitnipu09@lus.ac.bd",
  },
  {
    acronym: "SA",
    fullName: "Sabbir Ahmed",
    faculty: "THM",
    designation: "Adjunct Faculty,THM, LU",
    phone: "01626000868",
    email: "sabbir1621@gmail.com",
  },
];
